var lib = require('qiyilib');

var channels = [
    {
        name:'首页',
        url:'/index.html',
        type:'logic',
        tpls:{
            home:{
                id:'index',
                url:'/templates/pages/home.inc'
            }
        }
    },
    {
        name:'资讯',
        id:25,
        url:'/zixun/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'娱乐',
        id:7,
        url:'/yule/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'电视剧',
        id:2,
        url:'/dianshiju/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/dianshiju.inc',
                id:'dianshiju'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'电影',
        id:1,
        url:'/dianying/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/dianying.inc',
                id:'dianying'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'综艺',
        id:6,
        url:'/zongyi/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/zongyi.inc',
                id:'zongyi'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'动漫',
        id:4,
        url:'/dongman/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/dongman.inc',
                id:'dongman'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'片花',
        id:10,
        url:'/pianhua/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/pianhua.inc',
                id:'pianhua'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'少儿',
        id:15,
        url:'/shaoer/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'搞笑',
        id:22,
        url:'/fun/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/gaoxiao.inc',
                id:'gaoxiao'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'时尚',
        id:13,
        url:'/shishang/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/shishang.inc',
                id:'shishang'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'生活',
        id:21,
        url:'/life/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/shenghuo.inc',
                id:'shenghuo'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'音乐',
        id:5,
        url:'/yinyue/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yinyue.inc',
                id:'yinyue'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'体育',
        id:17,
        url:'/sports/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/sports.inc',
                id:'sports'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'微电影',
        id:16,
        url:'/weidianying/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/weidianying.inc',
                id:'weidianying'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'纪录片',
        id:3,
        url:'/jilupian/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/jilupian.inc',
                id:'jilupian'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'旅游',
        id:9,
        url:'/lvyou/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/lvyou.inc',
                id:'lvyou'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'广告',
        id:20,
        url:'/ad/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/guanggao.inc',
                id:'guanggao'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'财经',
        id:24,
        url:'/caijing/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'教育',
        id:12,
        url:'/edu/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/edu.inc',
                id:'edu'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'汽车',
        id:26,
        url:'/qiche/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'游戏',
        id:8,
        url:'/youxi/',
        type:'entity',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    },
    {
        name:'VIP会员',
        id:7,
        url:'http://vip.iqiyi.com/',
        type:'external',
        tpls:{
            home:{
                url:'/templates/pages/yule.inc',
                id:'yule'
            },
            detail:{
                url:'/templates/pages/yule.inc',
                id:'yulea'
            },
            play:{
                url:'/templates/pages/play.inc',
                id:'play'
            }
        }
    }
];

var Channels = {
    getDataByCid:function(cid){
        for(var i = 0; i < channels.length; i++){
            var channel = channels[i];
            if(channel.id === cid){
                return channel;
            }
        }
    },
    getDataByCname:function(cname){
        for(var i = 0; i < channels.length; i++){
            var channel = channels[i];
            if(channel.name === cname){
                return channel;
            }
        }
    }
};

module.exports = Channels;